project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - programa.qmd
    - programa-detallado.qmd
    - evaluacion.qmd
    - recursos/software.qmd
    - recursos/referencias.qmd
    - recursos/datasets.qmd

website:
  title: "MAT2409 - Análisis de datos II"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Programa"
        href: programa.qmd

  page-footer:
    right: "Creado con [Quarto](https://quarto.org/)"
    left: "© 2026 MAT2409 - Análisis de datos II | Contenido bajo licencia [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)"
    background: "#5d6d74"

format:
  html:
    theme: cosmo
    linkcolor: "#798b93"
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    code-tools: false
    fig-width: 8
    fig-height: 6
    fig-align: center

execute:
  eval: false
  warning: false
  message: false
  echo: true

editor: visual
